task/urls.py
from django.urls import path

from . import views

app_name = "task"
urlpatterns = [
    path("", views.index, name="index"),
    path("save/", views.save_task, name="save"),
    path("delete/<int:task_id>/", views.delete_task, name="delete"),
    path("complete/<int:task_id>/", views.complete_task, name="complete"),
]

todo_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    path('tasks/', include("task.urls")),
    path('admin/', admin.site.urls),
]

task/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    task = models.CharField(max_length=255)
    created_at = models.DateTimeField("Created At", auto_now_add=True)
    complete = models.BooleanField(default=False)
    
    class Meta:
        db_table = "tasks"

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

from .managers import CustomUserManager

class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField("Correo electrónico", unique=True)
    created_at = models.DateTimeField("Created at", auto_now_add=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ("email",)

class CustomUserChangeForm(UserChangeForm):
    pass

task/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse

from .models import Task
# Create your views here.
def index(request):
    tasks = Task.objects.all()
    tareas_completadas = list(filter(lambda t: (t.complete == 1), tasks))
    context = { "tasks":tasks, "tareas_completadas": len(tareas_completadas)}
    template = "task/index.html"
    return render(request, template, context)

def save_task(request):
    task = request.POST.get("txtTask", "")
    if task:
        t = Task(task=task)
        t.save()
    
    return redirect("/tasks")

def delete_task(request, task_id):
    Task.objects.filter(id=task_id).delete()
    return redirect("/tasks")

def complete_task(request, task_id):
    Task.objects.filter(id=task_id).update(complete=1)
    return redirect("task:index")

users/views.py
from django.shortcuts import render

# Create your views here.

task/templates/task/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>TODO App</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
      crossorigin="anonymous"
    />
    {% load static %}

    <link rel="stylesheet" href="{% static 'task/css/style.css' %}" />
  </head>
  <body>
    <main>
      <header>
        <h1>TODO App</h1>
      </header>
      <div class="todo">
        <form action="{% url 'task:save' %}" method="post">
          {% csrf_token %}
          <div class="todo-form line-bottom">
            <input
              type="text"
              class="todo-input"
              id="txtTask"
              placeholder="Nueva tarea"
              name="txtTask"
            />
            <button id="btnAdd" class="btn btn-add">+ Nueva Tarea</button>
          </div>
        </form>
        <ul class="todo-list">
          {% if tasks %} {% for task in tasks %}
          <li>
            <span class="{{ task.complete|yesno:'task-complete,' }}">{{task.task}}</span>
            <a href="{% url 'task:complete' task.id %}" class="btn btn-complete">Completar</a>
            <a href="{% url 'task:delete' task.id %}" class="btn btn-delete">Eliminar</a>
          </li>
          {% endfor %} {% endif %}
        </ul>
      </div>
      <div>
        <strong>Tareas completadas: </strong
        ><span class="task-completes-count">{{ tareas_completadas}}</span>
      </div>
    </main>
  </body>
</html>